#!/bin/bash -1
#PBS -l nodes=1:ppn=8,mem=15g,walltime=24:00:00
#PBS -m abe
#PBS -M haasx092@umn.edu
#PBS -o ~/main_GBS/run_cutadapt.out
#PBS -e ~/main_GBS/run_cutadapt.err

cd ~/main_GBS

module load cutadapt

for i in $(cat 190819_sample_list.txt); do
cutadapt -b TCGCTGTCTCTTATACACATCT $i/${i}_concatenated.fq.gz -o $i/${i}_trimmed.fq.gz 2> $i/${i}_cutadapt.err
done
